'use client'

import Head from 'next/head'
import Navbar from '../_homepage/Navbar'

/**
 * Header component.
 */
export default function Header() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
      </header>
    </>
  )
}
